# Generated by Django 3.0.6 on 2020-05-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.TextField()),
                ('leader_id', models.IntegerField()),
                ('leader_cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('co_leader_id', models.IntegerField()),
                ('co_leader_cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('choice1', models.TextField()),
                ('choice2', models.TextField()),
                ('choice3', models.TextField()),
                ('choice4', models.TextField()),
                ('choice5', models.TextField()),
                ('choice6', models.TextField()),
                ('choice7', models.TextField()),
                ('choice8', models.TextField()),
                ('choice9', models.TextField()),
                ('choice10', models.TextField()),
            ],
        ),
    ]
