# Generated by Django 3.0.6 on 2020-05-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='contact_mail',
            field=models.EmailField(default='ucchash886@gmail.com', max_length=254),
        ),
    ]
